/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatosRouteImport } from './routes/relatos'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as NetworkingRouteImport } from './routes/networking'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FrequenciasRouteImport } from './routes/frequencias'
import { Route as DeterminacoesRouteImport } from './routes/determinacoes'
import { Route as ArquetiposRouteImport } from './routes/arquetipos'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const RelatosRoute = RelatosRouteImport.update({
  id: '/relatos',
  path: '/relatos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkingRoute = NetworkingRouteImport.update({
  id: '/networking',
  path: '/networking',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequenciasRoute = FrequenciasRouteImport.update({
  id: '/frequencias',
  path: '/frequencias',
  getParentRoute: () => rootRouteImport,
} as any)
const DeterminacoesRoute = DeterminacoesRouteImport.update({
  id: '/determinacoes',
  path: '/determinacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquetiposRoute = ArquetiposRouteImport.update({
  id: '/arquetipos',
  path: '/arquetipos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/arquetipos': typeof ArquetiposRoute
  '/determinacoes': typeof DeterminacoesRoute
  '/frequencias': typeof FrequenciasRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/networking': typeof NetworkingRoute
  '/performance': typeof PerformanceRoute
  '/relatos': typeof RelatosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/arquetipos': typeof ArquetiposRoute
  '/determinacoes': typeof DeterminacoesRoute
  '/frequencias': typeof FrequenciasRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/networking': typeof NetworkingRoute
  '/performance': typeof PerformanceRoute
  '/relatos': typeof RelatosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/arquetipos': typeof ArquetiposRoute
  '/determinacoes': typeof DeterminacoesRoute
  '/frequencias': typeof FrequenciasRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/networking': typeof NetworkingRoute
  '/performance': typeof PerformanceRoute
  '/relatos': typeof RelatosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/arquetipos'
    | '/determinacoes'
    | '/frequencias'
    | '/login'
    | '/manual'
    | '/networking'
    | '/performance'
    | '/relatos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/arquetipos'
    | '/determinacoes'
    | '/frequencias'
    | '/login'
    | '/manual'
    | '/networking'
    | '/performance'
    | '/relatos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/arquetipos'
    | '/determinacoes'
    | '/frequencias'
    | '/login'
    | '/manual'
    | '/networking'
    | '/performance'
    | '/relatos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ArquetiposRoute: typeof ArquetiposRoute
  DeterminacoesRoute: typeof DeterminacoesRoute
  FrequenciasRoute: typeof FrequenciasRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  NetworkingRoute: typeof NetworkingRoute
  PerformanceRoute: typeof PerformanceRoute
  RelatosRoute: typeof RelatosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatos': {
      id: '/relatos'
      path: '/relatos'
      fullPath: '/relatos'
      preLoaderRoute: typeof RelatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networking': {
      id: '/networking'
      path: '/networking'
      fullPath: '/networking'
      preLoaderRoute: typeof NetworkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequencias': {
      id: '/frequencias'
      path: '/frequencias'
      fullPath: '/frequencias'
      preLoaderRoute: typeof FrequenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/determinacoes': {
      id: '/determinacoes'
      path: '/determinacoes'
      fullPath: '/determinacoes'
      preLoaderRoute: typeof DeterminacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquetipos': {
      id: '/arquetipos'
      path: '/arquetipos'
      fullPath: '/arquetipos'
      preLoaderRoute: typeof ArquetiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ArquetiposRoute: ArquetiposRoute,
  DeterminacoesRoute: DeterminacoesRoute,
  FrequenciasRoute: FrequenciasRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  NetworkingRoute: NetworkingRoute,
  PerformanceRoute: PerformanceRoute,
  RelatosRoute: RelatosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
